# Generated by Django 5.2.16 on 2026-10-04 18:15

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.CRM_CUSTOMER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceTemplate",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version_major",
                    models.IntegerField(blank=True, default=1, null=True),
                ),
                (
                    "version_minor",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "version_patch",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("version", models.CharField(blank=True, default="1.0.0", null=True)),
                (
                    "name",
                    models.CharField(max_length=128, verbose_name="Template Name"),
                ),
                (
                    "html_template",
                    models.TextField(verbose_name="HTML Template Snapshot"),
                ),
            ],
            options={
                "verbose_name": "Invoice Template",
                "verbose_name_plural": "Invoice Templates",
                "abstract": False,
                "swappable": "INVOICES_INVOICE_TEMPLATE_MODEL",
            },
        ),
        migrations.CreateModel(
            name="BillingOrganization",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("is_removed", models.BooleanField(default=False)),
                (
                    "id",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "organization_name",
                    models.CharField(max_length=255, verbose_name="Organization Name"),
                ),
                (
                    "billing_suffix",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional suffix appended to invoice sequence numbers (e.g. /2026-27 or -INV).",
                        max_length=32,
                        verbose_name="Billing Suffix",
                    ),
                ),
                (
                    "billing_start_sequence",
                    models.PositiveBigIntegerField(
                        default=1,
                        help_text="Initial sequence number for generated invoices.",
                        verbose_name="Billing Start Sequence",
                    ),
                ),
                (
                    "billing_current_sequence",
                    models.PositiveBigIntegerField(
                        default=0,
                        help_text="Current sequence counter tracker for generated invoices.",
                        verbose_name="Billing Current Sequence",
                    ),
                ),
                (
                    "removed_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Billing Organization",
                "verbose_name_plural": "Billing Organizations",
                "abstract": False,
                "swappable": "INVOICES_BILLING_ORGANIZATION_MODEL",
            },
        ),
        migrations.CreateModel(
            name="InvoiceAddress",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("is_removed", models.BooleanField(default=False)),
                (
                    "id",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "address_line_1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "address_line_2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("landmark", models.CharField(blank=True, max_length=128, null=True)),
                ("city", models.CharField(blank=True, max_length=128, null=True)),
                ("state", models.CharField(blank=True, max_length=128, null=True)),
                ("postal_code", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "country",
                    models.CharField(
                        blank=True, default="IN", max_length=64, null=True
                    ),
                ),
                (
                    "removed_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice Address",
                "verbose_name_plural": "Invoice Addresses",
                "abstract": False,
                "swappable": "INVOICES_INVOICE_ADDRESS_MODEL",
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("is_removed", models.BooleanField(default=False)),
                (
                    "id",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        db_index=True,
                        help_text="Unique identifier for the invoice generated by the billing organization sequence.",
                        max_length=64,
                        verbose_name="Invoice Number",
                    ),
                ),
                (
                    "invoice_date",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="Invoice Date",
                    ),
                ),
                (
                    "biller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to=settings.INVOICES_BILLING_ORGANIZATION_MODEL,
                        verbose_name="Billing Organization",
                    ),
                ),
                (
                    "removed_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "billing_address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="billing_invoices",
                        to=settings.INVOICES_INVOICE_ADDRESS_MODEL,
                        verbose_name="Billing Address",
                    ),
                ),
                (
                    "shipping_address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipping_invoices",
                        to=settings.INVOICES_INVOICE_ADDRESS_MODEL,
                        verbose_name="Shipping Address",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice",
                "verbose_name_plural": "Invoices",
                "abstract": False,
                "swappable": "INVOICES_INVOICE_MODEL",
            },
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("is_removed", models.BooleanField(default=False)),
                (
                    "id",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Item Name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="Price",
                    ),
                ),
                (
                    "discount_options",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Discount Options"
                    ),
                ),
                (
                    "HSN_code",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="HSN Code"
                    ),
                ),
                (
                    "current_stock",
                    models.IntegerField(default=0, verbose_name="Current Stock"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "removed_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice Item",
                "verbose_name_plural": "Invoice Items",
                "abstract": False,
                "swappable": "INVOICES_INVOICE_ITEM_MODEL",
            },
        ),
        migrations.CreateModel(
            name="InvoiceItemEntry",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("is_removed", models.BooleanField(default=False)),
                (
                    "id",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "item_name",
                    models.CharField(max_length=255, verbose_name="Item Name Snapshot"),
                ),
                (
                    "item_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Item Description Snapshot"
                    ),
                ),
                (
                    "HSN_code",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="HSN Code Snapshot",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        verbose_name="Unit Price Snapshot",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        max_digits=10,
                        verbose_name="Quantity",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_entries",
                        to=settings.INVOICES_INVOICE_MODEL,
                        verbose_name="Invoice",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional reference to source catalog item.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoice_entries",
                        to=settings.INVOICES_INVOICE_ITEM_MODEL,
                        verbose_name="Catalog Item",
                    ),
                ),
                (
                    "removed_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice Item Entry",
                "verbose_name_plural": "Invoice Item Entries",
                "abstract": False,
                "swappable": "INVOICES_INVOICE_ITEM_ENTRY_MODEL",
            },
        ),
        migrations.CreateModel(
            name="InvoiceItemFee",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("is_removed", models.BooleanField(default=False)),
                (
                    "id",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Rate percentage applied to the line entry amount.",
                        max_digits=6,
                        verbose_name="Rate (%)",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Description / Fee Name",
                    ),
                ),
                (
                    "auto_applied",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this tax/fee was automatically computed and attached.",
                        verbose_name="Auto Applied",
                    ),
                ),
                (
                    "item_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fees",
                        to=settings.INVOICES_INVOICE_ITEM_ENTRY_MODEL,
                        verbose_name="Invoice Item Entry",
                    ),
                ),
                (
                    "removed_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice Item Fee",
                "verbose_name_plural": "Invoice Item Fees",
                "abstract": False,
                "swappable": "INVOICES_INVOICE_ITEM_FEE_MODEL",
            },
        ),
        migrations.CreateModel(
            name="InvoiceParty",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("is_removed", models.BooleanField(default=False)),
                (
                    "id",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("suffix", models.CharField(blank=True, default=None, null=True)),
                ("first_name", models.CharField(blank=True, default=None, null=True)),
                ("middle_name", models.CharField(blank=True, default=None, null=True)),
                ("last_name", models.CharField(blank=True, default=None, null=True)),
                (
                    "business_name",
                    models.CharField(blank=True, default=None, null=True),
                ),
                (
                    "party_type",
                    models.CharField(
                        choices=[
                            ("customer", "Customer"),
                            ("distributor", "Distributor"),
                            ("supplier", "Supplier"),
                            ("vendor", "Vendor"),
                            ("other", "Other"),
                        ],
                        default="customer",
                        max_length=32,
                        verbose_name="Party Type",
                    ),
                ),
                (
                    "pending_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=14,
                        verbose_name="Pending Balance",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional reference to the source customer profile in CRM.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoice_parties",
                        to=settings.CRM_CUSTOMER_MODEL,
                        verbose_name="Linked CRM Customer",
                    ),
                ),
                (
                    "removed_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice Party",
                "verbose_name_plural": "Invoice Parties",
                "abstract": False,
                "swappable": "INVOICES_INVOICE_PARTY_MODEL",
            },
        ),
        migrations.AddField(
            model_name="invoice",
            name="party",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to=settings.INVOICES_INVOICE_PARTY_MODEL,
                verbose_name="Invoiced Party",
            ),
        ),
        migrations.CreateModel(
            name="InvoicePartyCategory",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("is_removed", models.BooleanField(default=False)),
                (
                    "id",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category_name",
                    models.CharField(
                        max_length=128, unique=True, verbose_name="Category Name"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "removed_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice Party Category",
                "verbose_name_plural": "Invoice Party Categories",
                "abstract": False,
                "swappable": "INVOICES_INVOICE_PARTY_CATEGORY_MODEL",
            },
        ),
        migrations.AddField(
            model_name="invoiceparty",
            name="party_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parties",
                to=settings.INVOICES_INVOICE_PARTY_CATEGORY_MODEL,
                verbose_name="Party Category",
            ),
        ),
        migrations.CreateModel(
            name="InvoicePartyEmail",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("is_removed", models.BooleanField(default=False)),
                (
                    "id",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email Address"),
                ),
                (
                    "email_type",
                    models.CharField(
                        choices=[
                            ("primary", "Primary"),
                            ("secondary", "Secondary"),
                            ("billing", "Billing"),
                            ("support", "Support"),
                            ("work", "Work"),
                            ("personal", "Personal"),
                            ("other", "Other"),
                        ],
                        default="primary",
                        max_length=32,
                        verbose_name="Email Type",
                    ),
                ),
                (
                    "invoice_party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emails",
                        to=settings.INVOICES_INVOICE_PARTY_MODEL,
                        verbose_name="Invoice Party",
                    ),
                ),
                (
                    "removed_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice Party Email",
                "verbose_name_plural": "Invoice Party Emails",
                "abstract": False,
                "swappable": "INVOICES_INVOICE_PARTY_EMAIL_MODEL",
            },
        ),
        migrations.CreateModel(
            name="InvoicePartyPhone",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("is_removed", models.BooleanField(default=False)),
                (
                    "id",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("phone", models.CharField(max_length=32, verbose_name="Phone Number")),
                (
                    "phone_type",
                    models.CharField(
                        choices=[
                            ("primary", "Primary"),
                            ("secondary", "Secondary"),
                            ("billing", "Billing"),
                            ("support", "Support"),
                            ("work", "Work"),
                            ("personal", "Personal"),
                            ("other", "Other"),
                        ],
                        default="primary",
                        max_length=32,
                        verbose_name="Phone Type",
                    ),
                ),
                (
                    "invoice_party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phones",
                        to=settings.INVOICES_INVOICE_PARTY_MODEL,
                        verbose_name="Invoice Party",
                    ),
                ),
                (
                    "removed_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice Party Phone",
                "verbose_name_plural": "Invoice Party Phones",
                "abstract": False,
                "swappable": "INVOICES_INVOICE_PARTY_PHONE_MODEL",
            },
        ),
        migrations.AddField(
            model_name="invoice",
            name="invoice_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to=settings.INVOICES_INVOICE_TEMPLATE_MODEL,
                verbose_name="Invoice Template",
            ),
        ),
        migrations.CreateModel(
            name="OrganizationAssets",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("is_removed", models.BooleanField(default=False)),
                (
                    "id",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "asset",
                    models.FileField(
                        upload_to="invoices/organization_assets/",
                        verbose_name="Asset File",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Asset Name")),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("logo", "Logo"),
                            ("signature", "Signature"),
                            ("stamp", "Stamp"),
                            ("header", "Header"),
                            ("footer", "Footer"),
                            ("other", "Other"),
                        ],
                        default="logo",
                        max_length=32,
                        verbose_name="Asset Type",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "billing_org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to=settings.INVOICES_BILLING_ORGANIZATION_MODEL,
                        verbose_name="Billing Organization",
                    ),
                ),
                (
                    "removed_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization Asset",
                "verbose_name_plural": "Organization Assets",
                "abstract": False,
                "swappable": "INVOICES_ORGANIZATION_ASSETS_MODEL",
            },
        ),
        migrations.CreateModel(
            name="OrganizationEmail",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("is_removed", models.BooleanField(default=False)),
                (
                    "id",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email Address"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("primary", "Primary"),
                            ("secondary", "Secondary"),
                            ("billing", "Billing"),
                            ("support", "Support"),
                            ("work", "Work"),
                            ("personal", "Personal"),
                            ("other", "Other"),
                        ],
                        default="primary",
                        max_length=32,
                        verbose_name="Email Type",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="Is Primary"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emails",
                        to=settings.INVOICES_BILLING_ORGANIZATION_MODEL,
                        verbose_name="Billing Organization",
                    ),
                ),
                (
                    "removed_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization Email",
                "verbose_name_plural": "Organization Emails",
                "abstract": False,
                "swappable": "INVOICES_ORGANIZATION_EMAIL_MODEL",
            },
        ),
        migrations.CreateModel(
            name="OrganizationFinancials",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("is_removed", models.BooleanField(default=False)),
                (
                    "id",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "aadhar",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="Aadhaar"
                    ),
                ),
                (
                    "GSTIN",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="GSTIN"
                    ),
                ),
                (
                    "PAN",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="PAN"
                    ),
                ),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_data",
                        to=settings.INVOICES_BILLING_ORGANIZATION_MODEL,
                        verbose_name="Billing Organization",
                    ),
                ),
                (
                    "removed_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization Financials",
                "verbose_name_plural": "Organization Financials",
                "abstract": False,
                "swappable": "INVOICES_ORGANIZATION_FINANCIALS_MODEL",
            },
        ),
        migrations.CreateModel(
            name="OrganizationPhone",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("is_removed", models.BooleanField(default=False)),
                (
                    "id",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("phone", models.CharField(max_length=32, verbose_name="Phone Number")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("primary", "Primary"),
                            ("secondary", "Secondary"),
                            ("billing", "Billing"),
                            ("support", "Support"),
                            ("work", "Work"),
                            ("personal", "Personal"),
                            ("other", "Other"),
                        ],
                        default="primary",
                        max_length=32,
                        verbose_name="Phone Type",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="Is Primary"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phones",
                        to=settings.INVOICES_BILLING_ORGANIZATION_MODEL,
                        verbose_name="Billing Organization",
                    ),
                ),
                (
                    "removed_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization Phone",
                "verbose_name_plural": "Organization Phones",
                "abstract": False,
                "swappable": "INVOICES_ORGANIZATION_PHONE_MODEL",
            },
        ),
    ]
