# Generated by Django 5.2.16 on 2026-10-03 11:47

import django.core.serializers.json
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="domain",
            options={"verbose_name": "Domain", "verbose_name_plural": "Domains"},
        ),
        migrations.AlterModelOptions(
            name="tenantbranding",
            options={
                "verbose_name": "Tenant Branding",
                "verbose_name_plural": "Tenant Brandings",
            },
        ),
        migrations.AlterModelOptions(
            name="tenantcontactinfo",
            options={
                "verbose_name": "Tenant Contact Info",
                "verbose_name_plural": "Tenant Contact Infos",
            },
        ),
        migrations.AlterModelOptions(
            name="tenants",
            options={"verbose_name": "Tenant", "verbose_name_plural": "Tenants"},
        ),
        migrations.RemoveField(
            model_name="tenantcontactinfo",
            name="value",
        ),
        migrations.AddField(
            model_name="tenantcontactinfo",
            name="contact_info",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                help_text="Contact information for the tenant in JSON format.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tenants",
            name="status_changed",
            field=model_utils.fields.MonitorField(
                default=django.utils.timezone.now,
                monitor="status",
                verbose_name="status changed",
            ),
        ),
        migrations.AlterField(
            model_name="tenantbranding",
            name="tenant",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="branding",
                to=settings.TENANTS_TENANT_MODEL,
            ),
        ),
    ]
