# Generated by Django 5.2.16 on 2026-10-04 20:09

import model_utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_alter_domain_options_alter_tenantbranding_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenants",
            name="status",
            field=model_utils.fields.StatusField(
                choices=[
                    ("provisioning", "Provisioning"),
                    ("ready", "Ready"),
                    ("failed", "Failed"),
                ],
                default="provisioning",
                max_length=100,
                no_check_for_status=True,
                verbose_name="status",
            ),
        ),
    ]
