import typing
from decimal import Decimal
from functools import cached_property

from django.conf import settings
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from core.utils.models import AbstractAddress, BaseModel, BaseVersioningModel

if typing.TYPE_CHECKING:
    from .items import AbstractInvoiceItemEntry
    from .organizations import AbstractBillingOrganization
    from .parties import AbstractInvoiceParty


class AbstractInvoiceAddress(BaseModel, AbstractAddress):
    """
    Abstract model for physical or billing addresses snapshotted during invoice creation.
    """

    class Meta:
        abstract = True
        verbose_name = _("Invoice Address")
        verbose_name_plural = _("Invoice Addresses")

    def __str__(self) -> str:
        return self.full_address or str(self.pk)


class AbstractInvoiceTemplate(BaseVersioningModel):
    """
    Abstract model snapshot for templates used to render invoices.
    """

    name = models.CharField(max_length=128, verbose_name=_("Template Name"))
    html_template = models.TextField(verbose_name=_("HTML Template Snapshot"))

    class Meta:
        abstract = True
        verbose_name = _("Invoice Template")
        verbose_name_plural = _("Invoice Templates")

    def __str__(self) -> str:
        return f"{self.name} (v{self.version})"


class AbstractInvoice(BaseModel):
    """
    Abstract Invoice model representing the immutable snapshot of a bill issued by an organization to a customer/party.
    """

    invoice_number = models.CharField(
        max_length=64,
        db_index=True,
        verbose_name=_("Invoice Number"),
        help_text=_(
            "Unique identifier for the invoice generated by the billing organization sequence."
        ),
    )
    invoice_date = models.DateField(
        default=timezone.localdate,
        verbose_name=_("Invoice Date"),
    )
    party: "AbstractInvoiceParty" = models.ForeignKey(
        settings.INVOICES_INVOICE_PARTY_MODEL,
        on_delete=models.PROTECT,
        related_name="invoices",
        verbose_name=_("Invoiced Party"),
    )
    biller: "AbstractBillingOrganization" = models.ForeignKey(
        settings.INVOICES_BILLING_ORGANIZATION_MODEL,
        on_delete=models.PROTECT,
        related_name="invoices",
        verbose_name=_("Billing Organization"),
    )
    billing_address = models.ForeignKey(
        settings.INVOICES_INVOICE_ADDRESS_MODEL,
        on_delete=models.PROTECT,
        related_name="billing_invoices",
        verbose_name=_("Billing Address"),
    )
    shipping_address = models.ForeignKey(
        settings.INVOICES_INVOICE_ADDRESS_MODEL,
        on_delete=models.PROTECT,
        null=True,
        blank=True,
        related_name="shipping_invoices",
        verbose_name=_("Shipping Address"),
    )
    invoice_template = models.ForeignKey(
        settings.INVOICES_INVOICE_TEMPLATE_MODEL,
        on_delete=models.PROTECT,
        null=True,
        blank=True,
        related_name="invoices",
        verbose_name=_("Invoice Template"),
    )

    class Meta:
        abstract = True
        verbose_name = _("Invoice")
        verbose_name_plural = _("Invoices")

    def __str__(self) -> str:
        return f"Invoice #{self.invoice_number} ({self.party})"

    def save(self, *args, **kwargs):
        """Auto-generate invoice number from biller sequence if not provided."""
        if not self.invoice_number and self.biller_id:
            self.invoice_number = self.biller.generate_next_invoice_number()

        if not self.shipping_address_id and self.billing_address_id:
            self.shipping_address = self.billing_address

        super().save(*args, **kwargs)

    @cached_property
    def entries(self) -> models.QuerySet["AbstractInvoiceItemEntry"]:
        """Return all item line entries for this invoice with prefetched relationships."""
        return self.item_entries.select_related("item").prefetch_related("fees").all()

    @cached_property
    def subtotal(self) -> Decimal:
        """Calculate net total for all line items before taxes/fees."""
        return sum((entry.total_price for entry in self.entries), Decimal("0.00"))

    @cached_property
    def total_fees(self) -> Decimal:
        """Calculate sum of all taxes and fees across all line item entries."""
        return sum((entry.total_fee_amount for entry in self.entries), Decimal("0.00"))

    @cached_property
    def grand_total(self) -> Decimal:
        """Calculate grand total bill amount (subtotal + total_fees)."""
        return self.subtotal + self.total_fees
