# Generated by Django 5.2.16 on 2026-10-04 18:15

import django.core.serializers.json
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.TENANTS_TENANT_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AbstractTenantConfiguration",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version_major",
                    models.IntegerField(blank=True, default=1, null=True),
                ),
                (
                    "version_minor",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "version_patch",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("version", models.CharField(blank=True, default="1.0.0", null=True)),
                (
                    "details",
                    models.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_configs",
                        to=settings.TENANTS_TENANT_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ConfigurationSchema",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("is_removed", models.BooleanField(default=False)),
                (
                    "id",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("interface_type", models.CharField()),
                (
                    "schema",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                (
                    "removed_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration Schema",
                "verbose_name_plural": "Configuration Schemas",
                "abstract": False,
                "swappable": "CONFIGURATIONS_CONFIGURATION_SCHEMA_MODEL",
            },
        ),
        migrations.CreateModel(
            name="Configuration",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version_major",
                    models.IntegerField(blank=True, default=1, null=True),
                ),
                (
                    "version_minor",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "version_patch",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("version", models.CharField(blank=True, default="1.0.0", null=True)),
                ("name", models.CharField(blank=True, max_length=124, null=True)),
                ("interface_type", models.CharField(choices=[])),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                (
                    "schema",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="configurations",
                        to=settings.CONFIGURATIONS_CONFIGURATION_SCHEMA_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration",
                "verbose_name_plural": "Configurations",
                "abstract": False,
                "swappable": "CONFIGURATIONS_CONFIGURATION_MODEL",
            },
        ),
        migrations.CreateModel(
            name="TenantConfiguration",
            fields=[
                (
                    "abstracttenantconfiguration_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="configurations.abstracttenantconfiguration",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "swappable": "CONFIGURATIONS_TENANT_CONFIGURATION_MODEL",
            },
            bases=("configurations.abstracttenantconfiguration",),
        ),
    ]
